### ISSUE TITLE
Depending on che flavor, use the upstream/downstream image puller image for the deployment

### ISSUE THREAD

**Issue by tomgeorge** [che-incubator/kubernetes-image-puller#33]
Based on discussions in https://github.com/eclipse/che-operator/pull/541, we should choose the correct image puller image based on Che flavor.

I think this can be done via an additional field in the ConfigMap, or by injecting an environment variable into the deployment.

**Comment by nickboldt** [comment]
here's the downstream image https://catalog.redhat.com/software/containers/codeready-workspaces/imagepuller-rhel8/5e42db8ed70cc54b02bd7ed6 that should be used when flavor=codeready

**Comment by ibuziuk** [comment]
Closing in favor of https://github.com/eclipse/che/issues/18569
