### ISSUE TITLE
Toleration support

### ISSUE THREAD

**Issue by kfox1111** [che-incubator/kubernetes-image-puller#34]
For certain clusters (heterogenious) you may need to be able to specify tolerations so that image pods can land on appropriate hardware.

**Comment by ibuziuk** [comment]
@kfox1111 we are currently tracking image puller issues in the https://github.com/eclipse/che/issues could you please report it there with the additional details. Thanks

**Comment by Sajadorouji** [comment]
https://github.com/che-incubator/kubernetes-image-puller/pull/42

**Comment by vikas027** [comment]
Hello @kfox1111 and @Sajadorouji ,

The above PR has been merged but I can't find `NODE_TOLERATION` in the [README.md](https://github.com/che-incubator/kubernetes-image-puller/blob/main/README.md) file

**Comment by d-m** [comment]
@vikas027 it looks like the PR wasn't merged, but was deleted when the master branch was switched to main: https://github.com/che-incubator/kubernetes-image-puller/pull/42#issuecomment-882605749

**Comment by ibuziuk** [comment]
we would really appreciate it if a new PR can be opened against 'main', also Eclipse Contributor Agreement needs to be signed before merging the PR - https://www.eclipse.org/legal/ECA.php
Thanks
