### ISSUE TITLE
not installable on OpenShift 4.8

### ISSUE THREAD

**Issue by rbaumgar** [che-incubator/kubernetes-image-puller#91]
try to install image-puller on OpenShift 4.8.17

- Pulling image "quay.io/eclipse/kubernetes-image-puller-operator:0.0.9"
- Error: container create failed: time="2021-11-15T14:30:13Z" level=error msg="container_linux.go:367: starting container process caused: exec: \"kubernetes-image-puller-operator\": executable file not found in $PATH"

**Comment by ibuziuk** [comment]
Closing. feel free to reopen
